### ISSUE TITLE
[Test Framework] Use web login name as the info "commit by"

### ISSUE THREAD

**Issue by Cidana-Emma** [Cidana-Developers/UnitTests-Task-manager#58]

**Comment by Kenny-Cidana** [comment]
It may be hard to achieve this goal, due to the Job build trigger is asynchronous.

API service send a command to Jenkins to trigger new build, but the build is not start immediately (just put it in its queue), when new job build actual start, Jenkins will notify API service and tell the actual build number and the person who trigger the new build

**Comment by Kenny-Cidana** [comment]
Hi Foch, please help to check if the Jenkins could provide some solution to let us build connection between job id & login user (of CTP, not Jenkins user)

**Comment by Kenny-Cidana** [comment]
find out new way and solve the issue

**Comment by Cidana-Emma** [comment]
Closed
